resources:
- name: hello-world
  type: git
  source:
    uri: https://github.com/benhorvath/hello-world.git
    branch: master

jobs:
- name: hello-world
  plan:
    - get: hello-world
      trigger: true
    - task: hello-world-task
      file: hello-world/hello-world-task.yml
    - task: create-file-task
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: busybox }
        outputs:
        - name: files
        run:
          path: sh -c 'ls -lha'

